//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Body { get; set; }
        public string FeaturedImage { get; set; }
        public int UserId { get; set; }
        public string AuthorName { get; set; }
        public int IsActive { get; set; }
        public int IsApproved { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual ApproveStatus ApproveStatus { get; set; }
        public virtual Users Users { get; set; }
    }
}
